version: v1
calculations:
  # 原始传感器组数据（直接引用，无需计算）
  - id: "bag_pressure"
    description: "袋内压"
    source: "VACUUM_PRESS"
    unit: "kPa"
    type: "sensor_group"
    
  - id: "curing_pressure"
    description: "罐压"
    source: "CURING_PRESS"
    unit: "kPa"
    type: "sensor_group"
    
  - id: "thermocouples"
    description: "温度传感器组"
    source: "thermocouples"
    unit: "℃"
    type: "sensor_group"
    
  - id: "leading_thermocouples"
    description: "领先热电偶"
    source: "leading_thermocouples"
    unit: "℃"
    type: "sensor_group"
    
  - id: "lagging_thermocouples"
    description: "滞后热电偶"
    source: "lagging_thermocouples"
    unit: "℃"
    type: "sensor_group"
    
  # 复杂计算项
  - id: "heating_rate"
    description: "温度变化速率"
    formula: "rate(thermocouples, step=1, axis=0, timestamps=timestamps)"
    sensors: ["thermocouples", "timestamps"]
    unit: "℃/min"
    type: "calculated"
    
  - id: "soaking_duration"
    description: "保温时间"
    formula: "intervals(all(thermocouples >= 174, axis=1), timestamps=timestamps)"
    sensors: ["thermocouples", "timestamps"]
    unit: "min"
    type: "calculated"
    
  - id: "thermocouple_cross_heating"
    description: "热电偶交叉"
    formula: "max(leading_thermocouples, axis=1) - min(lagging_thermocouples, axis=1)"
    sensors: ["leading_thermocouples", "lagging_thermocouples"]
    unit: "℃"
    type: "calculated"

  - id: "thermocouple_cross_cooling"
    description: "热电偶交叉"
    formula: "min(leading_thermocouples, axis=1) - max(lagging_thermocouples, axis=1)"
    sensors: ["leading_thermocouples", "lagging_thermocouples"]
    unit: "℃"
    type: "calculated"