version: v1
rules:
  - id: "bag_pressure_check_1"
    description: "通大气前阶段袋内压检查。袋内压(kPa)≤-74kPa"
    condition: "max(bag_pressure) <= -74"
    calculations: ["bag_pressure"]
    severity: "major"

  - id: "bag_pressure_check_2"
    description: "全局袋内压检查。袋内压(kPa)≤34kPa"
    condition: "max(bag_pressure) <= 34"
    calculations: ["bag_pressure"]
    severity: "major"

  - id: "curing_pressure_check_1"
    description: "通大气后阶段罐压检查。首个罐压(kPa)≥140kPa"
    condition: "first(curing_pressure) >= 140"
    calculations: ["curing_pressure"]
    severity: "major"

  - id: "curing_pressure_check_2"
    description: "加热至保温结束固化压力检查。压力应在600-650kPa范围内"
    condition: "min(curing_pressure) >= 600 and max(curing_pressure) <= 650"
    calculations: ["curing_pressure"]
    severity: "major"

  - id: "curing_pressure_check_3"
    description: "降温阶段固化压力检查。压力应在600-650kPa范围内"
    condition: "min(curing_pressure) >= 393 and max(curing_pressure) <= 650"
    calculations: ["curing_pressure"]
    severity: "major"
  
  - id: "thermocouples_check"
    description: "罐压下限时温度检查。罐压下限时温度应小于55℃"
    condition: "first(thermocouples) < 55"
    calculations: ["thermocouples"]
    severity: "critical"
    
  - id: "heating_rate_phase_1"
    description: "升温阶段1速率检查。55℃至150℃升温速率应在0.5-3℃/min范围内"
    condition: "min(heating_rate) >= 0.5 and max(heating_rate) <= 3.0"
    calculations: ["heating_rate"]
    severity: "major"
    
  - id: "heating_rate_phase_2"
    description: "升温阶段2速率检查。150℃至165℃升温速率应在0.15-3℃/min范围内"
    condition: "min(heating_rate) >= 0.15 and max(heating_rate) <= 3.0"
    calculations: ["heating_rate"]
    severity: "major"
    
  - id: "heating_rate_phase_3"
    description: "升温阶段3速率检查。165℃至174℃升温速率应在0.06-3℃/min范围内"
    condition: "min(heating_rate) >= 0.06 and max(heating_rate) <= 3.0"
    calculations: ["heating_rate"]
    severity: "major"
    
  - id: "soaking_temperature"
    description: "保温温度检查。保温温度应在174-186℃范围内"
    condition: "min(thermocouples) >= 174 and max(thermocouples) <= 186"
    calculations: ["thermocouples"]
    severity: "critical"
    
  - id: "soaking_time"
    description: "保温时间检查。保温时间应在120-999分钟范围内"
    condition: "max(soaking_duration) >= 120 and max(soaking_duration) <= 999"
    calculations: ["soaking_duration"]
    severity: "critical"

  - id: "cooling_rate"
    description: "降温速率检查。降温速率应在0-3℃/min范围内"
    condition: "min(heating_rate) >= -3 and max(heating_rate) <= 0"
    calculations: ["heating_rate"]
    severity: "major"
    
  - id: "thermocouple_cross_heating"
    description: "升温阶段热电偶交叉检查。升温阶段领先偶与滞后偶温差应≥-5.6℃"
    condition: "min(thermocouple_cross_heating) >= -5.6"
    calculations: ["thermocouple_cross_heating"]
    severity: "minor"
    
  - id: "thermocouple_cross_cooling"
    description: "降温阶段热电偶交叉检查。降温阶段领先偶与滞后偶温差应≤5.6℃"
    condition: "max(thermocouple_cross_cooling) <= 5.6"
    calculations: ["thermocouple_cross_cooling"]
    severity: "minor"
