version: v1
rules:
  - id: "pressure_at_lower_limit"
    name: "罐压下限时温度检查"
    description: "罐压达到下限时温度应小于55℃"
    condition: "max(thermocouples) < 55 when pressure >= 600"
    severity: "critical"
    
  - id: "heating_rate_phase_1"
    name: "升温阶段1速率检查"
    description: "55℃至150℃升温速率应在0.5-3℃/min范围内"
    condition: "0.5 <= heating_rate <= 3.0"
    calculation: "heating_rate"
    severity: "major"
    
  - id: "heating_rate_phase_2"
    name: "升温阶段2速率检查"
    description: "150℃至165℃升温速率应在0.15-3℃/min范围内"
    condition: "0.15 <= heating_rate <= 3.0"
    calculation: "heating_rate"
    severity: "major"
    
  - id: "heating_rate_phase_3"
    name: "升温阶段3速率检查"
    description: "165℃至174℃升温速率应在0.06-3℃/min范围内"
    condition: "0.06 <= heating_rate <= 3.0"
    calculation: "heating_rate"
    severity: "major"
    
  - id: "soaking_temperature"
    name: "保温温度检查"
    description: "保温温度应在174-186℃范围内"
    condition: "174 <= max(thermocouples) <= 186 during soaking"
    severity: "critical"
    
  - id: "soaking_time"
    name: "保温时间检查"
    description: "保温时间应在120-999分钟范围内"
    condition: "120 <= soaking_duration <= 999"
    calculation: "soaking_duration"
    severity: "critical"
    
  - id: "curing_pressure"
    name: "固化压力检查"
    description: "固化压力应在600-650kPa范围内"
    condition: "600 <= CURING_PRESS <= 650 during soaking"
    severity: "major"
    
  - id: "cooling_rate"
    name: "降温速率检查"
    description: "降温速率应在0-3℃/min范围内"
    condition: "0 <= cooling_rate <= 3.0"
    calculation: "cooling_rate"
    severity: "major"
    
  - id: "cooling_pressure"
    name: "降温压力检查"
    description: "降温压力应在393-650kPa范围内"
    condition: "393 <= CURING_PRESS <= 650 during cooling"
    severity: "major"
    
  - id: "thermocouple_cross_heating"
    name: "升温阶段热电偶交叉检查"
    description: "升温阶段领先偶与滞后偶温差应≥-5.6℃"
    condition: "min(leading_thermocouples) - max(lagging_thermocouples) >= -5.6 during heating"
    severity: "minor"
    
  - id: "thermocouple_cross_cooling"
    name: "降温阶段热电偶交叉检查"
    description: "降温阶段领先偶与滞后偶温差应≤5.6℃"
    condition: "max(leading_thermocouples) - min(lagging_thermocouples) <= 5.6 during cooling"
    severity: "minor"
    
  - id: "bag_pressure"
    name: "袋内压检查"
    description: "袋内压应≤34kPa"
    condition: "max(VACUUM_PRESS) <= 34"
    severity: "major"
    actions:
      - when: "34 < VACUUM_PRESS <= 136"
        then: "wait_for_ndt"
      - when: "VACUUM_PRESS > 136"
        then: "reject"