version: v1
sensor_groups:
  VACUUM_PRESS:
    description: "袋内压传感器（真空压力）"
    columns: "VPRB1"
    unit: "kPa"

  CURING_PRESS:
    description: "罐内压传感器"
    columns: "PRESS"
    unit: "kPa"
    
  thermocouples:
    description: "所有热电偶传感器"
    columns: "PTC10,PTC11,PTC23,PTC24"
    unit: "°C"
    
  leading_thermocouples:
    description: "前导热电偶传感器"
    columns: "PTC10,PTC11"
    unit: "°C"
    
  lagging_thermocouples:
    description: "滞后热电偶传感器"
    columns: "PTC23,PTC24"
    unit: "°C"

  # 时间戳
  timestamps:
    description: "时间戳列"
    columns: "timestamp"
    unit: "datetime"

